version: '3.4'

services:
  app:
    extends:
      file: docker/docker-compose.base.yml
      service: app

  mysql:
    extends:
      file: docker/docker-compose.base.yml
      service: mysql

  redis:
    extends:
      file: docker/docker-compose.base.yml
      service: redis

  mail:
    extends:
      file: docker/docker-compose.base.yml
      service: mailhog

volumes:
  mysql-data:
    driver: local
  redis-data:
    driver: local

networks:
  local-net:
    driver: "bridge"
