version: '3.4'

services:
  app:
    image: pnlinh/symfony:php${PHP_VERSION:-8.1}
    hostname: "${DOCKER_PREFIX_NAME}-app"
    container_name: "${DOCKER_PREFIX_NAME}-app"
    environment:
      PHP_IDE_CONFIG: serverName="${DOCKER_PREFIX_NAME}-app.docker.cli"
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@pgsql:5432/${POSTGRES_DB}?serverVersion=${POSTGRES_VERSION:-14}&charset=utf8
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - "${DOCKER_APP_PORT:-80}:80"
    volumes:
      - ./:/var/www/html
    networks:
      - local-net

  redis:
    image: redis:alpine
    container_name: "${DOCKER_PREFIX_NAME}-redis"
    ports:
      - "${DOCKER_REDIS_PORT:-6379}:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      retries: 3
      timeout: 5s
    networks:
      - local-net

  mail:
    image: mailhog/mailhog
    container_name: "${DOCKER_PREFIX_NAME}-mailhog"
    ports:
      - "${DOCKER_MAIL_PORT:-8025}:8025"
    networks:
      - local-net

  static-builder:
    build:
      context: .
      dockerfile: docker/node.Dockerfile
    image: pnlinh/symfony-encore
    container_name: symfony-encore
    volumes:
      - ./:/app

volumes:
  pgsql-data:
    driver: local
  redis-data:
    driver: local

networks:
  local-net:
    driver: "bridge"
