version: '3.4'

services:
    app:
        image: pnlinh/php:81
        hostname: laravel-app
        container_name: laravel-app
        environment:
            PHP_IDE_CONFIG: serverName=laravel.docker.cli
        extra_hosts:
            - host.docker.internal:host-gateway
        ports:
            - ${DOCKER_APP_PORT:-80}:80
        volumes:
            - ./:/var/www/html
        depends_on:
            - mysql
            - redis
            - mailhog

    mysql:
        image: mysql:8.0
        container_name: laravel-mysql
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
            MYSQL_ROOT_HOST: "%"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
            MYSQL_USER: "${DB_USERNAME}"
            MYSQL_DATABASE: "${DB_DATABASE}"
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        ports:
            - "${DOCKER_DB_PORT:-3306}:3306"
        volumes:
            - mysql-data:/var/lib/mysql
            - ./docker/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
            retries: 3
            timeout: 5s

    redis:
        image: redis:alpine
        ports:
            - "${DOCKER_REDIS_PORT:-6379}:6379"
        container_name: laravel-redis
        volumes:
            - redis-data:/data
        healthcheck:
            test: [ "CMD", "redis-cli", "ping" ]
            retries: 3
            timeout: 5s

    mailhog:
        image: mailhog/mailhog
        ports:
            - "${DOCKER_MAIL_PORT:-8025}:8025"
        container_name: laravel-mailhog

    static:
        build:
            context: .
            dockerfile: docker/Dockerfile.nodejs
        image: pnlinh/static-builder
        container_name: static-builder

volumes:
    mysql-data:
        driver: local
    redis-data:
        driver: local
