mysql:
  image: mysql:8.0
  container_name: "${DOCKER_PREFIX_NAME}-mysql"
  command: --default-authentication-plugin=mysql_native_password
  environment:
    MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
    MYSQL_ROOT_HOST: "%"
    MYSQL_PASSWORD: "${DB_PASSWORD}"
    MYSQL_USER: "${DB_USERNAME}"
    MYSQL_DATABASE: "${DB_DATABASE}"
    MYSQL_ALLOW_EMPTY_PASSWORD: 1
  ports:
    - "${DOCKER_MYSQL_PORT:-3306}:3306"
  volumes:
    - mysql-data:/var/lib/mysql
    - ./docker/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh
    - ./docker/database/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
#    - ./docker/database/mysql/data:/var/lib/mysql
#    - ./docker/database/mysql/logs:/var/log/mysql
  healthcheck:
    test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
    retries: 3
    timeout: 5s
  networks:
    - local-net
