pgsql:
  image: postgres:14-alpine3.16
  container_name: "${DOCKER_PREFIX_NAME}-pgsql"
  environment:
    POSTGRES_DB: "${POSTGRES_DB:-symfony}"
    POSTGRES_USER: "${POSTGRES_USER:-user}"
    POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-secret}"
  ports:
    - "${DOCKER_POSTGRES_PORT:-5432}:5432"
  volumes:
    - pgsql-data:/var/lib/postgresql/data
#    - ./docker/database/pgsql/create-testing-database.sql:/docker-entrypoint-initdb.d/10-create-testing-database.sql
#    - ./docker/database/pgsql/data:/var/lib/postgresql/data
  healthcheck:
    test: [ "CMD", "pg_isready", "-q", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_PASSWORD}" ]
    retries: 3
    timeout: 5s
  networks:
    - local-net
